"""HTTP presenter for transforming application DTOs to API responses.

Responsible for:
- Mapping internal database status values to external StatusType
- Adding human-readable statusLabel
- Converting field naming conventions (snake_case to camelCase)
- Adding fields required by external contract (reportingRatio)
"""

from __future__ import annotations

from mesiri.application.projects.dtos import ProjectDTO

from .responses import ProjectResponse

# Canonical status mapping from WhatsApp Assistant
_STATUS_DISPLAY = {
    "on_track": ("success", "On Track"),
    "at_risk": ("warning", "At Risk"),
    "critical": ("critical", "Critical"),
    "on_hold": ("neutral", "On Hold"),
    "completed": ("neutral", "Completed"),
    "archived": ("neutral", "Archived"),
}

_VALID_STATUS = {"on_track", "at_risk", "critical", "on_hold", "completed", "archived"}


class ProjectPresenter:
    """Presenter for transforming project DTOs to HTTP responses.

    Applies canonical status mapping and field transformations.
    """

    @staticmethod
    def to_response(dto: ProjectDTO) -> ProjectResponse:
        """Transform project DTO to HTTP response.

        Args:
            dto: Internal project DTO with database status values

        Returns:
            ProjectResponse with mapped status and canonical field names
        """
        # Map database status to external StatusType + label
        db_status = dto.status if dto.status in _VALID_STATUS else "on_track"
        status_type, status_label = _STATUS_DISPLAY[db_status]

        return ProjectResponse(
            id=dto.id,
            name=dto.name,
            location=dto.location,
            code=dto.code,
            client=dto.client,
            description=dto.description,
            status=status_type,
            statusLabel=status_label,
            progress=dto.progress,
            openIssues=dto.open_issues,  # Transform snake_case to camelCase
            reportingRatio=None,  # Not yet implemented
            reportingTimezone=dto.reporting_timezone,
            reportingCutoffTime=dto.reporting_cutoff_time,
            autoGenerateDpr=dto.auto_generate_dpr,
            requiredReportTypes=dto.required_report_types,
        )

    @staticmethod
    def to_response_list(dtos: list[ProjectDTO]) -> list[ProjectResponse]:
        """Transform list of DTOs to list of responses.

        Args:
            dtos: List of project DTOs

        Returns:
            List of HTTP responses
        """
        return [ProjectPresenter.to_response(dto) for dto in dtos]
