"""Projects domain router — org-scoped project and site management.

Endpoints
---------
GET  /projects                     list projects accessible to the caller
POST /projects                     create a new project  (admin / PM)
GET  /projects/{id}/sites          list sites for a project
POST /projects/{id}/sites          create a site  (admin / PM)

Architecture
------------
GET /projects flow:
HTTP Router → ListProjects Query → Handler → AuthorizationContext →
Project Repository → PostgreSQL → DTO → Presenter → Response
"""

from __future__ import annotations

import uuid

import sqlalchemy as sa
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncConnection

from ...application.projects.handlers import ListProjectsHandler
from ...application.projects.queries import ListProjects
from ...authorization.context import AuthorizationContext
from ...authorization.service import AuthorizationService
from ...infrastructure.postgres.dependency import get_db_conn
from ...infrastructure.postgres.repositories.projects import PostgresProjectRepository
from ..shared.auth import get_current_user, require_admin
from .presenter import ProjectPresenter
from .responses import ProjectResponse

router = APIRouter(prefix="/projects", tags=["projects"])

# ---------------------------------------------------------------------------
# Table definitions
# ---------------------------------------------------------------------------
_projects = sa.Table(
    "projects",
    sa.MetaData(),
    sa.Column("id", sa.UUID(as_uuid=True)),
    sa.Column("organization_id", sa.UUID(as_uuid=True)),
    sa.Column("name", sa.String),
    sa.Column("code", sa.String),
    sa.Column("location", sa.String),
    sa.Column("client", sa.String),
    sa.Column("description", sa.String),
    sa.Column("status", sa.String),
    sa.Column("progress", sa.Integer),
    sa.Column("open_issues", sa.Integer),
    sa.Column("created_at", sa.DateTime(timezone=True)),
    sa.Column("updated_at", sa.DateTime(timezone=True)),
    sa.Column("reporting_timezone", sa.String),
    sa.Column("reporting_cutoff_time", sa.String),
    sa.Column("auto_generate_dpr", sa.Boolean),
    sa.Column("required_report_types", sa.JSON),
)

_sites = sa.Table(
    "sites",
    sa.MetaData(),
    sa.Column("id", sa.UUID(as_uuid=True)),
    sa.Column("project_id", sa.UUID(as_uuid=True)),
    sa.Column("organization_id", sa.UUID(as_uuid=True)),
    sa.Column("name", sa.String),
    sa.Column("status", sa.String),
    sa.Column("created_at", sa.DateTime(timezone=True)),
    sa.Column("updated_at", sa.DateTime(timezone=True)),
)

_project_members = sa.Table(
    "project_members",
    sa.MetaData(),
    sa.Column("id", sa.UUID(as_uuid=True)),
    sa.Column("project_id", sa.UUID(as_uuid=True)),
    sa.Column("user_id", sa.UUID(as_uuid=True)),
    sa.Column("role", sa.String),
    sa.Column("created_at", sa.DateTime(timezone=True)),
)


# ---------------------------------------------------------------------------
# Schema definitions
# ---------------------------------------------------------------------------


class ProjectCreate(BaseModel):
    name: str
    code: str | None = None
    location: str | None = None
    client: str | None = None
    description: str | None = None
    reportingTimezone: str = "UTC"
    reportingCutoffTime: str = "18:00"
    autoGenerateDpr: bool = False
    requiredReportTypes: list[str] | None = None


class ProjectUpdate(BaseModel):
    name: str | None = None
    code: str | None = None
    location: str | None = None
    client: str | None = None
    description: str | None = None
    status: str | None = None
    reportingTimezone: str | None = None
    reportingCutoffTime: str | None = None
    autoGenerateDpr: bool | None = None
    requiredReportTypes: list[str] | None = None


class SiteResponse(BaseModel):
    id: uuid.UUID
    project_id: uuid.UUID
    name: str
    status: str


class SiteCreate(BaseModel):
    name: str


class SiteUpdate(BaseModel):
    name: str | None = None
    status: str | None = None


class ProjectMemberAdd(BaseModel):
    userId: uuid.UUID
    role: str = "SITE_ENGINEER"


class ProjectMemberResponse(BaseModel):
    userId: uuid.UUID
    email: str
    fullName: str
    role: str
    status: str


# ---------------------------------------------------------------------------
# Dependencies
# ---------------------------------------------------------------------------


async def get_auth_context(
    jwt_payload: dict = Depends(get_current_user),
    conn: AsyncConnection = Depends(get_db_conn),
) -> AuthorizationContext:
    """Resolve authorization context for the current request.

    Validates JWT, loads current user from database, verifies status,
    and resolves project access scope.
    """
    user_id = uuid.UUID(jwt_payload["sub"])
    org_id = uuid.UUID(jwt_payload["org"])
    role = jwt_payload.get("role", "user")

    auth_service = AuthorizationService(conn)
    return await auth_service.resolve_from_jwt(user_id, org_id, role)


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@router.get("", response_model=list[ProjectResponse])
async def list_projects(
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    """List all projects accessible to the authenticated user."""
    # Create repository and handler
    repository = PostgresProjectRepository(conn)
    handler = ListProjectsHandler(repository)

    # Execute query
    query = ListProjects()
    projects = await handler.handle(query, auth_context)

    # Transform to HTTP response
    return ProjectPresenter.to_response_list(projects)


@router.post("", response_model=ProjectResponse, status_code=201)
async def create_project(
    body: ProjectCreate,
    admin: dict = Depends(require_admin),
    conn: AsyncConnection = Depends(get_db_conn),
):
    org_id = admin.get("org")
    project_id = uuid.uuid4()
    await conn.execute(
        _projects.insert().values(
            id=project_id,
            organization_id=org_id,
            name=body.name,
            code=body.code,
            location=body.location,
            client=body.client,
            description=body.description,
            reporting_timezone=body.reportingTimezone,
            reporting_cutoff_time=body.reportingCutoffTime,
            auto_generate_dpr=body.autoGenerateDpr,
            required_report_types=body.requiredReportTypes,
        )
    )
    return ProjectResponse(
        id=project_id,
        name=body.name,
        code=body.code,
        location=body.location,
        client=body.client,
        description=body.description,
        status="success",
        statusLabel="On Track",
        progress=0,
        openIssues=0,
        reportingRatio=None,
        reportingTimezone=body.reportingTimezone,
        reportingCutoffTime=body.reportingCutoffTime,
        autoGenerateDpr=body.autoGenerateDpr,
        requiredReportTypes=body.requiredReportTypes,
    )


@router.get("/{project_id}", response_model=ProjectResponse)
async def get_project(
    project_id: uuid.UUID,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    query = sa.select(_projects).where(
        _projects.c.id == project_id,
        _projects.c.organization_id == auth_context.organization_id,
    )
    result = await conn.execute(query)
    row = result.first()
    if row is None:
        raise HTTPException(status_code=404, detail="Project not found")

    # Check project scope permissions
    if not auth_context.project_scope.grants_all_org_projects:
        if project_id not in auth_context.project_scope.project_ids:
            raise HTTPException(status_code=403, detail="Access denied to this project")

    from mesiri.application.projects.dtos import ProjectDTO
    dto = ProjectDTO(
        id=row.id,
        organization_id=row.organization_id,
        name=row.name,
        code=row.code,
        location=row.location,
        client=row.client,
        description=row.description,
        status=row.status or "on_track",
        progress=row.progress or 0,
        open_issues=row.open_issues or 0,
        reporting_timezone=row.reporting_timezone or "UTC",
        reporting_cutoff_time=row.reporting_cutoff_time or "18:00",
        auto_generate_dpr=bool(row.auto_generate_dpr),
        required_report_types=row.required_report_types or None,
    )
    return ProjectPresenter.to_response(dto)


@router.put("/{project_id}", response_model=ProjectResponse)
async def update_project(
    project_id: uuid.UUID,
    body: ProjectUpdate,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    if auth_context.role.upper() != "ADMIN":
        raise HTTPException(status_code=403, detail="Admin access required to edit project")

    query = sa.select(_projects).where(
        _projects.c.id == project_id,
        _projects.c.organization_id == auth_context.organization_id,
    )
    result = await conn.execute(query)
    row = result.first()
    if row is None:
        raise HTTPException(status_code=404, detail="Project not found")

    values = {}
    if body.name is not None:
        values["name"] = body.name
    if body.code is not None:
        values["code"] = body.code
    if body.location is not None:
        values["location"] = body.location
    if body.client is not None:
        values["client"] = body.client
    if body.description is not None:
        values["description"] = body.description
    if body.status is not None:
        status_map = {
            "success": "on_track",
            "warning": "at_risk",
            "critical": "critical",
            "neutral": "on_hold",
            "active": "on_track",
            "on_track": "on_track",
            "at_risk": "at_risk",
            "on_hold": "on_hold",
            "completed": "completed",
            "archived": "archived",
        }
        values["status"] = status_map.get(body.status, body.status)
    if body.reportingTimezone is not None:
        values["reporting_timezone"] = body.reportingTimezone
    if body.reportingCutoffTime is not None:
        values["reporting_cutoff_time"] = body.reportingCutoffTime
    if body.autoGenerateDpr is not None:
        values["auto_generate_dpr"] = body.autoGenerateDpr
    if body.requiredReportTypes is not None:
        values["required_report_types"] = body.requiredReportTypes

    if values:
        await conn.execute(
            _projects.update()
            .where(_projects.c.id == project_id)
            .values(**values)
        )

    # Re-fetch
    refetch = await conn.execute(
        sa.select(_projects).where(_projects.c.id == project_id)
    )
    row = refetch.first()

    from mesiri.application.projects.dtos import ProjectDTO
    dto = ProjectDTO(
        id=row.id,
        organization_id=row.organization_id,
        name=row.name,
        code=row.code,
        location=row.location,
        client=row.client,
        description=row.description,
        status=row.status or "on_track",
        progress=row.progress or 0,
        open_issues=row.open_issues or 0,
        reporting_timezone=row.reporting_timezone or "UTC",
        reporting_cutoff_time=row.reporting_cutoff_time or "18:00",
        auto_generate_dpr=bool(row.auto_generate_dpr),
        required_report_types=row.required_report_types or None,
    )
    return ProjectPresenter.to_response(dto)


@router.delete("/{project_id}", status_code=204)
async def archive_project(
    project_id: uuid.UUID,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    if auth_context.role.upper() != "ADMIN":
        raise HTTPException(status_code=403, detail="Admin access required to archive project")

    query = sa.select(_projects).where(
        _projects.c.id == project_id,
        _projects.c.organization_id == auth_context.organization_id,
    )
    result = await conn.execute(query)
    row = result.first()
    if row is None:
        raise HTTPException(status_code=404, detail="Project not found")

    await conn.execute(
        _projects.update()
        .where(_projects.c.id == project_id)
        .values(status="archived")
    )
    return


@router.get("/{project_id}/sites", response_model=list[SiteResponse])
async def list_sites(
    project_id: uuid.UUID,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    if not auth_context.project_scope.grants_all_org_projects:
        if project_id not in auth_context.project_scope.project_ids:
            raise HTTPException(status_code=404, detail="Project not found")

    proj_result = await conn.execute(
        sa.select(_projects.c.id).where(
            _projects.c.id == project_id,
            _projects.c.organization_id == auth_context.organization_id,
        )
    )
    if proj_result.first() is None:
        raise HTTPException(status_code=404, detail="Project not found")

    site_scope = auth_context.site_scope_for_project(project_id)
    if site_scope.grants_no_sites:
        return []

    query = sa.select(_sites).where(_sites.c.project_id == project_id)
    if not site_scope.grants_all_sites:
        query = query.where(_sites.c.id.in_(site_scope.site_ids))

    result = await conn.execute(query)
    return [
        SiteResponse(
            id=r.id,
            project_id=r.project_id,
            name=r.name,
            status=r.status or "active",
        )
        for r in result.fetchall()
    ]


@router.post("/{project_id}/sites", response_model=SiteResponse, status_code=201)
async def create_site(
    project_id: uuid.UUID,
    body: SiteCreate,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    if auth_context.role.upper() != "ADMIN":
        raise HTTPException(status_code=403, detail="Admin access required")

    proj_result = await conn.execute(
        sa.select(_projects.c.id).where(
            _projects.c.id == project_id,
            _projects.c.organization_id == auth_context.organization_id,
        )
    )
    if proj_result.first() is None:
        raise HTTPException(status_code=404, detail="Project not found")

    site_id = uuid.uuid4()
    await conn.execute(
        _sites.insert().values(
            id=site_id,
            project_id=project_id,
            organization_id=auth_context.organization_id,
            name=body.name,
            status="active",
        )
    )
    return SiteResponse(
        id=site_id,
        project_id=project_id,
        name=body.name,
        status="active",
    )


@router.put("/{project_id}/sites/{site_id}", response_model=SiteResponse)
async def update_site(
    project_id: uuid.UUID,
    site_id: uuid.UUID,
    body: SiteUpdate,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    if auth_context.role.upper() != "ADMIN":
        raise HTTPException(status_code=403, detail="Admin access required to edit site")

    query = sa.select(_sites).where(
        _sites.c.id == site_id,
        _sites.c.project_id == project_id,
        _sites.c.organization_id == auth_context.organization_id,
    )
    result = await conn.execute(query)
    row = result.first()
    if row is None:
        raise HTTPException(status_code=404, detail="Site not found")

    values = {}
    if body.name is not None:
        values["name"] = body.name
    if body.status is not None:
        values["status"] = body.status

    if values:
        await conn.execute(
            _sites.update()
            .where(_sites.c.id == site_id)
            .values(**values)
        )

    refetch = await conn.execute(
        sa.select(_sites).where(_sites.c.id == site_id)
    )
    row = refetch.first()
    return SiteResponse(
        id=row.id,
        project_id=row.project_id,
        name=row.name,
        status=row.status or "active",
    )


@router.delete("/{project_id}/sites/{site_id}", status_code=204)
async def archive_site(
    project_id: uuid.UUID,
    site_id: uuid.UUID,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    if auth_context.role.upper() != "ADMIN":
        raise HTTPException(status_code=403, detail="Admin access required to archive site")

    query = sa.select(_sites).where(
        _sites.c.id == site_id,
        _sites.c.project_id == project_id,
        _sites.c.organization_id == auth_context.organization_id,
    )
    result = await conn.execute(query)
    row = result.first()
    if row is None:
        raise HTTPException(status_code=404, detail="Site not found")

    await conn.execute(
        _sites.update()
        .where(_sites.c.id == site_id)
        .values(status="archived")
    )
    return


@router.get("/{project_id}/members", response_model=list[ProjectMemberResponse])
async def list_project_members(
    project_id: uuid.UUID,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    proj_result = await conn.execute(
        sa.select(_projects.c.id).where(
            _projects.c.id == project_id,
            _projects.c.organization_id == auth_context.organization_id,
        )
    )
    if proj_result.first() is None:
        raise HTTPException(status_code=404, detail="Project not found")

    query = (
        sa.select(
            _project_members.c.user_id,
            _project_members.c.role.label("member_role"),
            sa.text("u.email"),
            sa.text("u.full_name"),
            sa.text("u.status"),
        )
        .select_from(
            _project_members.join(
                sa.text("users u"),
                _project_members.c.user_id == sa.text("u.id"),
            )
        )
        .where(_project_members.c.project_id == project_id)
    )
    result = await conn.execute(query)
    return [
        ProjectMemberResponse(
            userId=r.user_id,
            email=r.email,
            fullName=r.full_name,
            role=r.member_role,
            status=r.status,
        )
        for r in result.fetchall()
    ]


@router.post("/{project_id}/members", response_model=ProjectMemberResponse, status_code=201)
async def add_project_member(
    project_id: uuid.UUID,
    body: ProjectMemberAdd,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    if auth_context.role.upper() != "ADMIN":
        raise HTTPException(status_code=403, detail="Admin access required to add member")

    proj_result = await conn.execute(
        sa.select(_projects.c.id).where(
            _projects.c.id == project_id,
            _projects.c.organization_id == auth_context.organization_id,
        )
    )
    if proj_result.first() is None:
        raise HTTPException(status_code=404, detail="Project not found")

    user_result = await conn.execute(
        sa.select(sa.text("id, email, full_name, status")).where(
            sa.text("id = :user_id AND organization_id = :org_id")
        ),
        {"user_id": body.userId, "org_id": auth_context.organization_id},
    )
    user_row = user_result.first()
    if user_row is None:
        raise HTTPException(status_code=404, detail="User not found in organization")

    try:
        member_id = uuid.uuid4()
        await conn.execute(
            _project_members.insert().values(
                id=member_id,
                project_id=project_id,
                user_id=body.userId,
                role=body.role,
            )
        )
    except Exception as e:
        if "unique" in str(e).lower() or "23505" in str(e):
            raise HTTPException(status_code=409, detail="User is already a member of this project")
        raise

    return ProjectMemberResponse(
        userId=user_row.id,
        email=user_row.email,
        fullName=user_row.full_name,
        role=body.role,
        status=user_row.status,
    )


@router.delete("/{project_id}/members/{user_id}", status_code=204)
async def remove_project_member(
    project_id: uuid.UUID,
    user_id: uuid.UUID,
    auth_context: AuthorizationContext = Depends(get_auth_context),
    conn: AsyncConnection = Depends(get_db_conn),
):
    if auth_context.role.upper() != "ADMIN":
        raise HTTPException(status_code=403, detail="Admin access required to remove member")

    proj_result = await conn.execute(
        sa.select(_projects.c.id).where(
            _projects.c.id == project_id,
            _projects.c.organization_id == auth_context.organization_id,
        )
    )
    if proj_result.first() is None:
        raise HTTPException(status_code=404, detail="Project not found")

    await conn.execute(
        _project_members.delete().where(
            _project_members.c.project_id == project_id,
            _project_members.c.user_id == user_id,
        )
    )
    return
