"""Generic tabular PDF rendering, fpdf2-based.

Generalizes domains/dpr/pdf.py's approach (a single hardcoded DPR layout)
into a plain "columns + rows" renderer any caller can use -- e.g. the
WhatsApp assistant's finance-query "send as PDF" workflow (runtime/
inbound_journey.py imports this directly, same in-process pattern
runtime/dpr_request_query.py and friends already use to call backend code).

Pure function, no I/O -- unit-testable without a live database. fpdf2 is
imported lazily so the core test suite runs without it installed (mirrors
domains/dpr/pdf.py's own lazy import).
"""

from __future__ import annotations

_PAGE_WIDTH_MM = 210 - 2 * 15  # A4 minus 15mm margins each side


def render_table_pdf(
    *,
    title: str,
    subtitle: str | None,
    columns: list[str],
    rows: list[list[str]],
    column_widths: list[float] | None = None,
    empty_message: str = "No records found.",
) -> bytes:
    """Render one flat table (a title, optional subtitle, header row, and
    data rows) to PDF bytes. `column_widths` (mm) must match `columns`'
    length if given; otherwise columns split the page width evenly."""
    from fpdf import FPDF

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(15, 15, 15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
    if subtitle:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(90, 90, 90)
        pdf.cell(0, 6, subtitle, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    widths = column_widths or [_PAGE_WIDTH_MM / len(columns)] * len(columns)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(230, 230, 230)
    for header, width in zip(columns, widths, strict=False):
        pdf.cell(width, 7, header, border=1, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    if not rows:
        pdf.cell(sum(widths), 7, empty_message, border=1)
        pdf.ln()
    for row in rows:
        for value, width in zip(row, widths, strict=False):
            pdf.cell(width, 7, str(value) if value is not None else "-", border=1)
        pdf.ln()

    # See domains/dpr/pdf.py's identical comment: auto_page_break must be off
    # here, or fpdf2 can start a fresh page right before drawing the footer.
    pdf.set_auto_page_break(auto=False)
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 10, "Generated by Mesiri", align="C")

    return bytes(pdf.output())
