import { api } from './api'
import type { ProjectItem, SiteItem } from './scope-types'

export interface Project {
  id: string
  name: string
  code: string | null
  client: string | null
  location: string | null
  description: string | null
  status: string // mapped from backend (success, warning, critical, neutral)
  statusLabel: string
  progress: number
  openIssues: number
  reportingRatio: string | null
  reportingTimezone: string
  reportingCutoffTime: string
  autoGenerateDpr: boolean
  requiredReportTypes: string[] | null
}

export interface Site {
  id: string
  projectId: string
  name: string
  status: string
}

export interface ProjectMember {
  userId: string
  email: string
  fullName: string
  role: string
  status: string
}

export async function fetchProjects(): Promise<ProjectItem[]> {
  const res = await api.get<Array<{ id: string; name: string }>>('/projects')
  return res.data.map((p) => ({ id: p.id, name: p.name }))
}

export async function fetchProjectsFull(): Promise<Project[]> {
  const res = await api.get<Project[]>('/projects')
  return res.data
}

export async function fetchProject(projectId: string): Promise<Project> {
  const res = await api.get<Project>(`/projects/${projectId}`)
  return res.data
}

export async function createProject(payload: Partial<Project>): Promise<Project> {
  const res = await api.post<Project>('/projects', {
    name: payload.name,
    code: payload.code,
    client: payload.client,
    location: payload.location,
    description: payload.description,
  })
  return res.data
}


export async function updateProject(projectId: string, payload: Partial<Project>): Promise<Project> {
  const res = await api.put<Project>(`/projects/${projectId}`, {
    name: payload.name,
    code: payload.code,
    client: payload.client,
    location: payload.location,
    description: payload.description,
    status: payload.status,
    reportingTimezone: payload.reportingTimezone,
    reportingCutoffTime: payload.reportingCutoffTime,
    autoGenerateDpr: payload.autoGenerateDpr,
    requiredReportTypes: payload.requiredReportTypes,
  })
  return res.data
}

export async function archiveProject(projectId: string): Promise<void> {
  await api.delete(`/projects/${projectId}`)
}

export async function fetchSites(projectId: string): Promise<SiteItem[]> {
  const res = await api.get<Array<{ id: string; name: string; project_id: string }>>(
    `/projects/${projectId}/sites`
  )
  return res.data.map((s) => ({ id: s.id, name: s.name, projectId: s.project_id }))
}

export async function fetchSitesFull(projectId: string): Promise<Site[]> {
  const res = await api.get<Array<{ id: string; name: string; project_id: string; status: string }>>(
    `/projects/${projectId}/sites`
  )
  return res.data.map((s) => ({
    id: s.id,
    projectId: s.project_id,
    name: s.name,
    status: s.status,
  }))
}

export async function createSite(projectId: string, payload: { name: string }): Promise<Site> {
  const res = await api.post<{ id: string; name: string; project_id: string; status: string }>(
    `/projects/${projectId}/sites`,
    payload
  )
  return {
    id: res.data.id,
    projectId: res.data.project_id,
    name: res.data.name,
    status: res.data.status,
  }
}

export async function updateSite(
  projectId: string,
  siteId: string,
  payload: { name?: string; status?: string }
): Promise<Site> {
  const res = await api.put<{ id: string; name: string; project_id: string; status: string }>(
    `/projects/${projectId}/sites/${siteId}`,
    payload
  )
  return {
    id: res.data.id,
    projectId: res.data.project_id,
    name: res.data.name,
    status: res.data.status,
  }
}

export async function archiveSite(projectId: string, siteId: string): Promise<void> {
  await api.delete(`/projects/${projectId}/sites/${siteId}`)
}

export async function fetchProjectMembers(projectId: string): Promise<ProjectMember[]> {
  const res = await api.get<ProjectMember[]>(`/projects/${projectId}/members`)
  return res.data
}

export async function addProjectMember(
  projectId: string,
  payload: { userId: string; role: string }
): Promise<ProjectMember> {
  const res = await api.post<ProjectMember>(`/projects/${projectId}/members`, payload)
  return res.data
}

export async function removeProjectMember(projectId: string, userId: string): Promise<void> {
  await api.delete(`/projects/${projectId}/members/${userId}`)
}
