import * as React from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { updateProject, type Project } from '@/lib/projects'

const REPORT_TYPES = [
  { value: 'Work Progress', label: 'Work Progress' },
  { value: 'Workforce', label: 'Workforce (Labour)' },
  { value: 'Equipment & Machinery', label: 'Equipment & Machinery' },
  { value: 'Fuel', label: 'Fuel & Energy' },
  { value: 'Material In', label: 'Material In (GRN)' },
  { value: 'Material Out', label: 'Material Out (Usage)' },
  { value: 'Expenses', label: 'Expenses' },
  { value: 'Petty Cash', label: 'Petty Cash' },
  { value: 'Issues / Delays', label: 'Issues & Delays' },
  { value: 'Safety', label: 'Safety Log' },
  { value: 'General Updates', label: 'General Updates' },
]

interface ProjectReportingTabProps {
  project: Project
}

export function ProjectReportingTab({ project }: ProjectReportingTabProps) {
  const queryClient = useQueryClient()
  const [timezone, setTimezone] = React.useState('UTC')
  const [cutoffTime, setCutoffTime] = React.useState('18:00')
  const [autoDpr, setAutoDpr] = React.useState(false)
  const [reportTypes, setReportTypes] = React.useState<string[]>([])
  const [savingConfig, setSavingConfig] = React.useState(false)
  const [configSuccess, setConfigSuccess] = React.useState(false)

  // Sync reporting config fields from project response
  React.useEffect(() => {
    if (project) {
      setTimezone(project.reportingTimezone || 'UTC')
      setCutoffTime(project.reportingCutoffTime || '18:00')
      setAutoDpr(project.autoGenerateDpr || false)
      setReportTypes(project.requiredReportTypes || [])
    }
  }, [project])

  const handleUpdateReportingConfig = async (e: React.FormEvent) => {
    e.preventDefault()
    setSavingConfig(true)
    setConfigSuccess(false)

    try {
      await updateProject(project.id, {
        reportingTimezone: timezone,
        reportingCutoffTime: cutoffTime,
        autoGenerateDpr: autoDpr,
        requiredReportTypes: reportTypes,
      })
      queryClient.invalidateQueries({ queryKey: ['project-details', project.id] })
      setConfigSuccess(true)
    } catch (err: any) {
      alert(err.response?.data?.detail || 'Failed to update reporting config.')
    } finally {
      setSavingConfig(false)
    }
  }

  const toggleReportType = (type: string) => {
    setReportTypes((prev) =>
      prev.includes(type) ? prev.filter((t) => t !== type) : [...prev, type]
    )
  }

  return (
    <Card className="rounded-none border-border/70 shadow-none">
      <CardHeader className="pb-3 border-b">
        <CardTitle className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">
          Daily Reporting Rules
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-4">
        <form onSubmit={handleUpdateReportingConfig} className="max-w-xl space-y-4 text-xs">
          {configSuccess && (
            <div className="bg-emerald-500/10 border border-emerald-500 text-emerald-700 dark:text-emerald-400 p-2.5 rounded text-xs">
              Reporting configuration updated successfully!
            </div>
          )}

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="grid gap-1.5">
              <Label htmlFor="repTimezone">Reporting Timezone</Label>
              <Input
                id="repTimezone"
                value={timezone}
                onChange={(e) => setTimezone(e.target.value)}
                placeholder="e.g. UTC, Asia/Kolkata"
                required
              />
            </div>

            <div className="grid gap-1.5">
              <Label htmlFor="repCutoff">Daily Cutoff Time</Label>
              <Input
                id="repCutoff"
                value={cutoffTime}
                onChange={(e) => setCutoffTime(e.target.value)}
                placeholder="e.g. 18:00"
                required
              />
            </div>
          </div>

          <div className="flex items-center gap-2 py-1">
            <input
              id="repAutoDpr"
              type="checkbox"
              checked={autoDpr}
              onChange={(e) => setAutoDpr(e.target.checked)}
              className="rounded border-border/80 text-primary focus:ring-primary size-4"
            />
            <Label htmlFor="repAutoDpr" className="cursor-pointer">
              Automatically generate Daily Progress Report (DPR) at cutoff
            </Label>
          </div>

          <div className="space-y-1.5">
            <Label>Required Report Types</Label>
            <div className="grid grid-cols-2 gap-2 border p-3 rounded bg-muted/5 max-h-[200px] overflow-y-auto">
              {REPORT_TYPES.map((type) => {
                const isChecked = reportTypes.includes(type.value)
                return (
                  <label key={type.value} className="flex items-center gap-2 cursor-pointer hover:text-foreground">
                    <input
                      type="checkbox"
                      checked={isChecked}
                      onChange={() => toggleReportType(type.value)}
                      className="rounded border-border/80 text-primary focus:ring-primary size-3.5"
                    />
                    <span className="text-[11px] text-muted-foreground">{type.label}</span>
                  </label>
                )
              })}
            </div>
          </div>

          <Button type="submit" disabled={savingConfig} className="text-xs h-8">
            {savingConfig ? 'Saving Configurations...' : 'Save Configuration'}
          </Button>
        </form>
      </CardContent>
    </Card>
  )
}
